Merging CSVs

In [ ]:
import pandas as pd

# List of CSV file paths
files = [
    "/content/drive/MyDrive/UIDAI_Dataset/api_data_aadhar_biometric/api_data_aadhar_biometric_0_500000.csv",
    "/content/drive/MyDrive/UIDAI_Dataset/api_data_aadhar_biometric/api_data_aadhar_biometric_500000_1000000.csv",
    "/content/drive/MyDrive/UIDAI_Dataset/api_data_aadhar_biometric/api_data_aadhar_biometric_1000000_1500000.csv",
    "/content/drive/MyDrive/UIDAI_Dataset/api_data_aadhar_biometric/api_data_aadhar_biometric_1500000_1861108.csv"
]

# Read and merge all CSVs
df = pd.concat([pd.read_csv(file) for file in files], ignore_index=True)

# Save merged file
df.to_csv("/content/drive/MyDrive/UIDAI_DATA/data_aadhar_biometric.csv", index=False)

print("CSV files merged successfully!")

CSV files merged successfully!

In [ ]:
import pandas as pd

# List of CSV file paths
files = [
    "/content/drive/MyDrive/UIDAI_Dataset/api_data_aadhar_demographic/api_data_aadhar_demographic_0_500000.csv",
    "/content/drive/MyDrive/UIDAI_Dataset/api_data_aadhar_demographic/api_data_aadhar_demographic_500000_1000000.csv",
    "/content/drive/MyDrive/UIDAI_Dataset/api_data_aadhar_demographic/api_data_aadhar_demographic_1000000_1500000.csv",
    "/content/drive/MyDrive/UIDAI_Dataset/api_data_aadhar_demographic/api_data_aadhar_demographic_1500000_2000000.csv",
    "/content/drive/MyDrive/UIDAI_Dataset/api_data_aadhar_demographic/api_data_aadhar_demographic_2000000_2071700.csv"

]

# Read and merge all CSVs
df = pd.concat([pd.read_csv(file) for file in files], ignore_index=True)

# Save merged file
df.to_csv("/content/drive/MyDrive/UIDAI_DATA/data_aadhar_demographic.csv", index=False)

print("CSV files merged successfully!")

CSV files merged successfully!

In [ ]:
import pandas as pd

# List of CSV file paths
files = [
  "/content/drive/MyDrive/UIDAI_Dataset/api_data_aadhar_enrolment/api_data_aadhar_enrolment_0_500000.csv",
  "/content/drive/MyDrive/UIDAI_Dataset/api_data_aadhar_enrolment/api_data_aadhar_enrolment_500000_1000000.csv",
  "/content/drive/MyDrive/UIDAI_Dataset/api_data_aadhar_enrolment/api_data_aadhar_enrolment_1000000_1006029.csv"
]

# Read and merge all CSVs
df = pd.concat([pd.read_csv(file) for file in files], ignore_index=True)

# Save merged file
df.to_csv("/content/drive/MyDrive/UIDAI_DATA/data_aadhar_enrolment.csv", index=False)

print("CSV files merged successfully!")

CSV files merged successfully!

Start

In [ ]:
import numpy as np
import pandas as pd
import re

In [ ]:
df_bio = pd.read_csv("/content/drive/MyDrive/UIDAI_DATA/data_aadhar_biometric.csv")
df_demo = pd.read_csv("/content/drive/MyDrive/UIDAI_DATA/data_aadhar_demographic.csv")
df_enroll = pd.read_csv("/content/drive/MyDrive/UIDAI_DATA/data_aadhar_enrolment.csv")

In [ ]:
df_bio

,date,state,district,pincode,bio_age_5_17,bio_age_17_
0,01-03-2025,Haryana,Mahendragarh,123029,280,577
1,01-03-2025,Bihar,Madhepura,852121,144,369
2,01-03-2025,Jammu and Kashmir,Punch,185101,643,1091
3,01-03-2025,Bihar,Bhojpur,802158,256,980
4,01-03-2025,Tamil Nadu,Madurai,625514,271,815
...,...,...,...,...,...,...
1861103,29-12-2025,West Bengal,Uttar Dinajpur,733201,4,9
1861104,29-12-2025,West Bengal,Uttar Dinajpur,733213,0,1
1861105,29-12-2025,West Bengal,West Midnapore,721304,0,3
1861106,29-12-2025,West Bengal,West Midnapore,721451,2,0
1861107,29-12-2025,West Bengal,West Midnapore,721457,0,1

In [ ]:
df_demo.head()

,date,state,district,pincode,demo_age_5_17,demo_age_17_
0,01-03-2025,Uttar Pradesh,Gorakhpur,273213,49,529
1,01-03-2025,Andhra Pradesh,Chittoor,517132,22,375
2,01-03-2025,Gujarat,Rajkot,360006,65,765
3,01-03-2025,Andhra Pradesh,Srikakulam,532484,24,314
4,01-03-2025,Rajasthan,Udaipur,313801,45,785

In [ ]:
df_enroll.head()

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
0,02-03-2025,Meghalaya,East Khasi Hills,793121,11,61,37
1,09-03-2025,Karnataka,Bengaluru Urban,560043,14,33,39
2,09-03-2025,Uttar Pradesh,Kanpur Nagar,208001,29,82,12
3,09-03-2025,Uttar Pradesh,Aligarh,202133,62,29,15
4,09-03-2025,Karnataka,Bengaluru Urban,560016,14,16,21

In [ ]:
df_bio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1861108 entries, 0 to 1861107
Data columns (total 6 columns):
 #   Column        Dtype
---  ------        -----
 0   date          object
 1   state         object
 2   district      object
 3   pincode       int64
 4   bio_age_5_17  int64
 5   bio_age_17_   int64
dtypes: int64(3), object(3)
memory usage: 85.2+ MB

In [ ]:
df_demo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2071700 entries, 0 to 2071699
Data columns (total 6 columns):
 #   Column         Dtype
---  ------         -----
 0   date           object
 1   state          object
 2   district       object
 3   pincode        int64
 4   demo_age_5_17  int64
 5   demo_age_17_   int64
dtypes: int64(3), object(3)
memory usage: 94.8+ MB

In [ ]:
df_enroll.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1006029 entries, 0 to 1006028
Data columns (total 7 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   date            1006029 non-null  object
 1   state           1006029 non-null  object
 2   district        1006029 non-null  object
 3   pincode         1006029 non-null  int64
 4   age_0_5         1006029 non-null  int64
 5   age_5_17        1006029 non-null  int64
 6   age_18_greater  1006029 non-null  int64
dtypes: int64(4), object(3)
memory usage: 53.7+ MB

In [ ]:
df_bio.columns

Index(['date', 'state', 'district', 'pincode', 'bio_age_5_17', 'bio_age_17_'], dtype='object')

In [ ]:
df_demo.columns

Index(['date', 'state', 'district', 'pincode', 'demo_age_5_17',
       'demo_age_17_'],
      dtype='object')

In [ ]:
df_enroll.columns

Index(['date', 'state', 'district', 'pincode', 'age_0_5', 'age_5_17',
       'age_18_greater'],
      dtype='object')

**Data Cleaning & Standardization**

In [ ]:
def clean_state_text(x):
    if pd.isna(x):
        return x
    x = x.strip()
    x = re.sub(r'\s+', ' ', x)
    x = re.sub(r'\s*&\s*', ' and ', x)
    x = x.title()
    return x

def standardize_state(x):
    return STATE_MAPPING.get(x, x)


def clean_district_text(x):
    if pd.isna(x):
        return x

    x = str(x)
    x = re.sub(r'[＊*?•]', '', x)
    x = re.sub(r'[-–—]', ' ', x)
    x = re.sub(r'\s*&\s*', ' and ', x)
    x = re.sub(r'[()]', '', x)
    x = re.sub(r'\s+', ' ', x)

    return x.strip().title()

def standardize_district(x):

    return DISTRICT_MAP.get(x, x)

In [ ]:
for df in [df_bio, df_demo, df_enroll]:
    df['state'] = df['state'].apply(clean_state_text)
    df['district'] = df['district'].apply(clean_district_text)

In [ ]:
df_enroll['district'].unique()

array(['East Khasi Hills', 'Bengaluru Urban', 'Kanpur Nagar', 'Aligarh',
       'Sitamarhi', 'Bahraich', 'Firozabad', 'Purbi Champaran',
       'Maharajganj', 'Aurangabad', 'Ghaziabad', 'Faridabad', 'Madhubani',
       'Sikar', 'Bhagalpur', 'Amritsar', 'Gurugram',
       'Gautam Buddha Nagar', 'West Delhi', 'Bhind', 'Gwalior', 'Katni',
       'Coochbehar', 'Lucknow', 'Dinajpur Uttar', 'Marigaon', 'Kokrajhar',
       'Agra', 'Haridwar', 'Nagaon', 'Parbhani', 'West Khasi Hills',
       'North West Delhi', 'West Jaintia Hills', 'Unnao', 'Saharanpur',
       'Dibrugarh', 'Udalguri', 'Chirang', 'Kamrup', 'Dhubri', 'Jaunpur',
       'Thane', 'Dhemaji', 'Banas Kantha', 'Tinsukia', 'Spsr Nellore',
       'Barpeta', 'Sonitpur', 'Baksa', 'Ludhiana', 'Patan', 'Kanchipuram',
       'Patna', 'Lakhimpur', 'Bongaigaon', 'Vadodara', 'Nainital',
       'Dehradun', 'Hojai', 'Dohad', 'Morbi', 'Raipur', 'Gorakhpur',
       'Bulandshahr', 'Mathura', 'Pashchim Champaran', 'Bijapur',
       'Deoghar', 'Muzaffarpur', 'Banda', 'Kachchh', 'Ri Bhoi', 'Darrang',
       'Ashok Nagar', 'Darjeeling', 'North Cachar Hills', 'Ranchi',
       'Surat', 'Nanded', 'Bengaluru', 'Jorhat', 'Gir Somnath',
       'Kamrup Metro', 'Goalpara', 'Bhavnagar', 'Golaghat', 'Nagpur',
       'Cooch Behar', 'Jalgaon', 'Hingoli', 'Ahmadnagar', 'Gandhinagar',
       'North 24 Parganas', 'Munger', 'Kohima', 'Jalor', 'Kheda',
       'Nalbari', 'Palghar', 'Jodhpur', 'Central Delhi', 'Gaya',
       'Sabarkantha', 'Dimapur', 'Cachar', 'Banaskantha', 'Kheri',
       'Rajkot', 'Satara', 'Betul', 'West Karbi Anglong', 'South Delhi',
       'Raigad', 'Uttar Dinajpur', 'Guna', 'Kaimur Bhabua', 'Dholpur',
       'Churachandpur', 'West Champaran', 'Bharuch', 'Jhargram',
       'Khargone', 'Chhotaudepur', 'Mumbai Suburban', 'Hailakandi',
       'Panchmahals', 'South Salmara Mankachar', 'Budaun', 'Kanpur Dehat',
       'Porbandar', 'West Garo Hills', 'Kapurthala', 'South Garo Hills',
       'Nagaur', 'Mysuru', 'Mahesana', 'Churu', 'Hyderabad',
       'Kancheepuram', 'Varanasi', 'Lohardaga', 'North Garo Hills',
       'Chhatarpur', 'Nadia', 'Purnia', 'Gurgaon', 'Charaideo', 'Jaipur',
       'Saran', 'Morena', 'Dhar', 'Dahod', 'Devbhumi Dwarka',
       'East Champaran', 'Tapi', 'Baghpat', 'Fatehpur',
       'South West Khasi Hills', 'Yadgir', 'Nandurbar', 'Etawah',
       'Jalpaiguri', 'Jabalpur', 'Shamli', 'Sibsagar', 'Barwani', 'Botad',
       'Junagadh', 'Balrampur', 'Bara Banki', 'Shivpuri', 'Beed',
       'Shahjahanpur', 'Jamnagar', 'Chandrapur', 'Durg',
       'K.V. Rangareddy', 'Sirohi', 'Alipurduar', 'South West Delhi',
       'Gonda', 'East Jaintia Hills', 'Bareilly', 'Bundi', 'Solapur',
       'Sitapur', 'Dumka', 'Sultanpur', 'Karbi Anglong', 'Bikaner',
       'Phek', 'Raisen', 'Shrawasti', 'East Delhi', 'Jhabua', 'Unakoti',
       'Indore', 'Bhopal', 'Dungarpur', 'Chandauli', 'Bharatpur',
       'Mainpuri', 'Godda', 'Muzaffarnagar', 'Siddharthnagar', 'Datia',
       'West Tripura', 'Medchal Malkajgiri', 'Sagar', 'Sheopur',
       'Arvalli', 'Surendra Nagar', 'Malda', 'Amreli', 'Alwar',
       'Ambedkar Nagar', 'Madurai', 'Pilibhit', 'Champhai', 'Valsad',
       'Pakur', 'Vaishali', 'Vidisha', 'Karimganj', 'Biswanath',
       'Burhanpur', 'Kaushambi', 'Pune', 'Punch', 'Jehanabad', 'Jalaun',
       'Etah', 'Meerut', 'Baran', 'Sangrur', 'Karauli', 'Anand',
       'Longleng', 'Chandigarh', 'Jamui', 'South Sikkim', 'Panna',
       'East Garo Hills', 'Jhalawar', 'Shahdara', 'Kalaburagi',
       'Thanjavur', 'Peren', 'Tuensang', 'Mahisagar', 'Hoshiarpur',
       'Noklak', 'Sukma', 'Khandwa', 'Ajmer', 'West Sikkim', 'Latur',
       'Basti', 'Satna', 'Gurdaspur', 'Hazaribagh', 'Azamgarh', 'Udaipur',
       'Kolkata', 'Rampur', 'The Dangs', 'East Singhbhum', 'Alirajpur',
       'Sas Nagar Mohali', 'South West Garo Hills', 'Moradabad', 'Kota',
       'Dewas', 'Navsari', 'Chumukedima', 'Ahmedabad', 'Nabarangapur',
       'Pali', 'Amroha', 'Saiha', 'Dakshin Dinajpur', 'Bijnor',
       'Pudukkottai', 'Bangalore Rural', 'Kalimpong', 'Deoria',
       'Baramula', 'Gopalganj', 'Prayagraj', 'Lalitpur', 'Mewat', 'Hapur',
       'Jammu', 'Bishnupur', 'Saharsa', 'Arwal', 'Hathras', 'Lawngtlai',
       'Nashik', 'Yavatmal', 'Cuddalore', 'Kollam', 'Patiala', 'Katihar',
       'Malappuram', 'Birbhum', 'Siwan', 'Dhule', 'Baloda Bazar',
       'Washim', 'Coimbatore', 'Lunglei', 'Imphal West', 'Kushinagar',
       'Thiruvananthapuram', 'Sangli', 'Ahmadabad', 'Lakhisarai',
       'Bengaluru Rural', '24 Paraganas North', 'Dima Hasao', 'Banka',
       'Salem', 'Dadra And Nagar Haveli', 'Dang', 'Kaithal', 'Vellore',
       'Shravasti', 'Nalanda', 'Jaisalmer', 'Kallakurichi', 'Farrukhabad',
       'Medinipur West', 'Araria', 'Sonipat', 'Chatra',
       'Gaurella Pendra Marwahi', 'Visakhapatanam', 'Buldhana',
       'Amravati', 'Hardoi', 'Dhalai', 'Ernakulam', 'New Delhi',
       'Bhilwara', 'Ramanathapuram', 'Mon', 'Raichur', 'North Delhi',
       'Rohtak', 'Gumla', 'Barmer', 'Kurukshetra', 'Nuh', 'Ashoknagar',
       'Thrissur', 'S.A.S Nagar', 'North East Delhi', 'Purba Bardhaman',
       'Ambala', 'Panipat', 'Darbhanga', 'Ayodhya', 'Khunti', 'Sivasagar',
       'Hisar', 'Sivaganga', 'Siddharth Nagar', 'West Kameng', 'Kullu',
       'Khordha', 'Barabanki', 'Chengalpattu', 'Ahmednagar', 'Jalore',
       'Nawada', 'Hooghly', '24 Paraganas South', 'Chennai',
       'Surendranagar', 'Mumbai', 'Nabarangpur', 'Sabar Kantha',
       'Ramanagara', 'Wokha', 'West Singhbhum', 'Sepahijala',
       'Samastipur', 'Zunheboto', 'East Singhbum', 'Sambhal',
       'Chittorgarh', 'Panch Mahals', 'Bidar', 'Tonk', 'Longding',
       'Jhansi', 'Howrah', 'Raigarh', 'Giridih', 'Akola', 'North Goa',
       'Vijayapura', 'Begusarai', 'Ranga Reddy', 'Thiruvallur',
       'Bhadradri Kothagudem', 'Hanumangarh', 'Kannur', 'Tarn Taran',
       'Majuli', 'Balaghat', 'Kiphire', 'Dinajpur Dakshin', 'East Nimar',
       'Osmanabad', 'Dhanbad', 'Kasganj', 'Shopian', 'Sehore', 'Kannauj',
       'Narsinghpur', 'Bilaspur', 'Kolasib', 'Sawai Madhopur',
       'North Tripura', 'Kushi Nagar', 'Prakasam', 'Bhojpur',
       'Hoshangabad', 'Doda', 'Mokokchung', 'Gomati', 'Krishna',
       'Kurnool', 'Mahabub Nagar', 'Mahbubnagar', 'Medak', 'N. T. R',
       'Nalgonda', 'Nandyal', 'Nellore', 'Palnadu', 'Rangareddi',
       'Sri Potti Sriramulu Nellore', 'Sri Sathya Sai', 'Srikakulam',
       'Tirupati', 'Visakhapatnam', 'Vizianagaram', 'Warangal',
       'West Godavari', 'Y. S. R', 'Changlang', 'East Kameng', 'Tawang',
       'West Siang', 'Bajali', 'Sribhumi', 'Buxar', 'Khagaria',
       'Kishanganj', 'Madhepura', 'Rohtas', 'Sheohar', 'Supaul', 'Bastar',
       'Bemetara', 'Gariyaband', 'Jashpur', 'Kawardha', 'Kondagaon',
       'Korba', 'Manendragarh Chirmiri Bharatpur', 'Rajnandgaon', 'Sakti',
       'Sarangarh Bilaigarh', 'Surajpur', 'Surguja', 'South Goa',
       'Narmada', 'Bhiwani', 'Charkhi Dadri', 'Fatehabad', 'Jhajjar',
       'Jind', 'Karnal', 'Mahendragarh', 'Rewari', 'Sirsa',
       'Yamuna Nagar', 'Hamirpur', 'Kangra', 'Mandi', 'Sirmaur', 'Solan',
       'Una', 'Anantnag', 'Badgam', 'Bandipore', 'Budgam', 'Kargil',
       'Kathua', 'Kupwara', 'Leh', 'Pulwama', 'Rajouri', 'Ramban',
       'Reasi', 'Samba', 'Srinagar', 'Udhampur', 'Bokaro', 'Garhwa',
       'Hazaribag', 'Jamtara', 'Latehar', 'Palamau', 'Palamu',
       'Purbi Singhbhum', 'Ramgarh', 'Sahebganj', 'Seraikela Kharsawan',
       'Simdega', 'Bagalkot', 'Ballari', 'Bangalore', 'Belagavi',
       'Belgaum', 'Bellary', 'Chamarajanagar', 'Chamrajanagar',
       'Chamrajnagar', 'Chickmagalur', 'Chikkaballapur', 'Chikkamagaluru',
       'Chikmagalur', 'Chitradurga', 'Dakshina Kannada', 'Davanagere',
       'Davangere', 'Dharwad', 'Gadag', 'Gulbarga', 'Hassan', 'Haveri',
       'Kodagu', 'Kolar', 'Koppal', 'Mandya', 'Mysore', 'Ramanagar',
       'Shimoga', 'Shivamogga', 'Tumakuru', 'Tumkur', 'Udupi',
       'Uttara Kannada', 'Vijayanagara', 'Alappuzha', 'Idukki',
       'Kasaragod', 'Kasargod', 'Kottayam', 'Kozhikode', 'Palakkad',
       'Pathanamthitta', 'Wayanad', 'Agar Malwa', 'Anuppur', 'Chhindwara',
       'Damoh', 'Dindori', 'Harda', 'Maihar', 'Mandla', 'Mandsaur',
       'Narmadapuram', 'Narsimhapur', 'Neemuch', 'Niwari', 'Rajgarh',
       'Ratlam', 'Rewa', 'Seoni', 'Shahdol', 'Shajapur', 'Sidhi',
       'Singrauli', 'Tikamgarh', 'Ujjain', 'West Nimar', 'Ahmed Nagar',
       'Bhandara', 'Buldana', 'Chhatrapati Sambhajinagar', 'Gadchiroli',
       'Gondiya', 'Jalna', 'Kolhapur', 'Mumbai City', 'Ratnagiri',
       'Sindhudurg', 'Wardha', 'Senapati', 'Tamenglong', 'Aizawl',
       'Angul', 'Nicobar', 'South Andaman', 'Adilabad',
       'Alluri Sitharama Raju', 'Anakapalli', 'Anantapur', 'Ananthapur',
       'Ananthapuramu', 'Bapatla', 'Chittoor', 'Cuddapah',
       'Dr. B. R. Ambedkar Konaseema', 'East Godavari', 'Eluru', 'Guntur',
       'Kakinada', 'Karimnagar', 'Khammam', 'Anugul', 'Balangir',
       'Baleswar', 'Bargarh', 'Baudh', 'Bhadrak', 'Boudh', 'Cuttack',
       'Debagarh', 'Dhenkanal', 'Gajapati', 'Ganjam', 'Jajpur',
       'Jagatsinghapur', 'Jagatsinghpur', 'Jajapur', 'Kalahandi',
       'Kandhamal', 'Kendrapara', 'Kendujhar', 'Khorda', 'Koraput',
       'Malkangiri', 'Mayurbhanj', 'Nayagarh', 'Nuapada', 'Puri',
       'Rayagada', 'Sambalpur', 'Sonapur', 'Subarnapur', 'Sundargarh',
       'Sundergarh', 'Baleshwar', 'Pondicherry', 'Karaikal', 'Puducherry',
       'Yanam', 'Barnala', 'Bathinda', 'Faridkot', 'Fatehgarh Sahib',
       'Ferozepur', 'Firozpur', 'Jalandhar', 'Malerkotla', 'Mansa',
       'Muktsar', 'Pathankot', 'Rupnagar', 'Shaheed Bhagat Singh Nagar',
       'Sri Muktsar Sahib', 'Banswara', 'Chittaurgarh', 'Dausa',
       'Ganganagar', 'Jhunjhunun', 'Pratapgarh', 'Rajsamand', 'East',
       'North Sikkim', 'South', 'Ariyalur', 'Dharmapuri', 'Dindigul',
       'Erode', 'Kanniyakumari', 'Kanyakumari', 'Karur', 'Krishnagiri',
       'Mayiladuthurai', 'Nagapattinam', 'Namakkal', 'Perambalur',
       'Ranipet', 'Tenkasi', 'The Nilgiris', 'Theni', 'Thiruvarur',
       'Thoothukkudi', 'Tiruchirappalli', 'Tirunelveli', 'Tirupattur',
       'Tiruppur', 'Tiruvallur', 'Tiruvannamalai', 'Villupuram',
       'Viluppuram', 'Virudhunagar', 'Hanumakonda', 'Jagitial', 'Jangoan',
       'Jayashankar Bhupalpally', 'Jogulamba Gadwal', 'Kamareddy',
       'Komaram Bheem', 'Mahabubabad', 'Mahabubnagar', 'Mancherial',
       'Medchal−Malkajgiri', 'Mulugu', 'Nagarkurnool', 'Narayanpet',
       'Nirmal', 'Nizamabad', 'Peddapalli', 'Rajanna Sircilla',
       'Sangareddy', 'Siddipet', 'Suryapet', 'Vikarabad', 'Wanaparthy',
       'Warangal Rural', 'Warangal Urban', 'Yadadri.', 'Khowai',
       'South Tripura', 'Allahabad', 'Amethi', 'Auraiya', 'Ballia',
       'Bhadohi', 'Chitrakoot', 'Faizabad', 'Ghazipur', 'Mahoba', 'Mau',
       'Mirzapur', 'Rae Bareli', 'Sant Kabir Nagar', 'Sant Ravidas Nagar',
       'Sonbhadra', 'Almora', 'Bageshwar', 'Chamoli', 'Garhwal',
       'Pauri Garhwal', 'Pithoragarh', 'Rudraprayag', 'Tehri Garhwal',
       'Udham Singh Nagar', 'Uttarkashi', 'Bankura', 'Barddhaman',
       'Bardhaman', 'Darjiling', 'East Midnapore', 'Haora', 'Koch Bihar',
       'Maldah', 'Murshidabad', 'North Twenty Four Parganas',
       'Paschim Bardhaman', 'Paschim Medinipur', 'Purba Medinipur',
       'Purulia', 'Puruliya', 'South 24 Parganas', 'South Dinajpur',
       'South Twenty Four Parganas', 'West Midnapore', 'North East',
       'Parvathipuram Manyam', 'Kurung Kumey', 'Lohit',
       'Lower Dibang Valley', 'Papum Pare', 'Upper Siang', 'Aurangabadbh',
       'Purba Champaran', 'Purnea', 'Sheikhpura', 'Balod', 'Dhamtari',
       'Gaurela Pendra Marwahi', 'Janjgir Champa', 'Kabeerdham', 'Kanker',
       'Khairagarh Chhuikhadan Gandai', 'Koriya', 'Mahasamund',
       'Mohla Manpur Ambagarh Chouki', 'Mungeli', 'Narayanpur', 'Palwal',
       'Chamba', 'Shimla', 'Ganderbal', 'Kodarma', 'Pakaur', 'Sahibganj',
       'Hasan', 'Lakshadweep', 'Mauganj', 'Umaria',
       'Chatrapati Sambhaji Nagar', 'Mumbai Sub Urban', 'Imphal East',
       'Thoubal', 'Ukhrul', 'Eastern West Khasi Hills', 'Mamit',
       'Serchhip', 'Andamans', 'North And Middle Andaman', 'Annamayya',
       'K.V.Rangareddy', 'Karim Nagar', 'Rangareddy', 'Bulandshahar',
       'Hugli', 'North Dinajpur', 'Jharsuguda', 'Fazilka', 'Moga',
       'North', 'Chandel', 'Kakching', 'S.A.S Nagarmohali', 'Jhunjhunu',
       'East Sikkim', 'West', 'Lower Subansiri', 'Namsai', 'Sheikpura',
       'Dakshin Bastar Dantewada', 'Daman', 'Panchkula', 'Kishtwar',
       'Shupiyan', 'Pashchimi Singhbhum', 'Pandhurna', 'Bid',
       'Jyotiba Phule Nagar', 'Sant Ravidas Nagar Bhadohi', 'Meluri',
       'Dhaulpur', 'Anjaw', 'East Siang', 'Tamulpur District',
       'Dantewada', 'Koderma', 'Dharashiv', 'Gondia', 'Kulgam', 'Jiribam',
       'Saitual', 'Kra Daadi', 'Upper Subansiri', 'Bhabua', 'Champawat',
       'Kamle', 'Mammit', 'Shamator', 'Nawanshahr', 'Jangaon', '100000',
       'Monghyr', 'Uttar Bastar Kanker', 'South East Delhi', 'Samstipur',
       'Diu', 'Najafgarh', 'Kinnaur', 'Tuticorin', 'Siang', 'Tirap',
       'Namchi', 'Hardwar', 'Niuland', 'Shi Yomi', 'Khawzawl',
       'Lahul And Spiti', 'Nicobars', 'Lower Siang', 'Yamunanagar',
       'Raebareli', 'Hawrah', 'Bengaluru South', 'Raigarhmh',
       'Tirupathur', 'Dibang Valley', 'Deeg', 'Leparada',
       'Medchalmalkajgiri', 'Medinipur', 'Mohalla Manpur Ambagarh Chowki',
       'Tseminyu', 'Mahrajganj', 'Hnahthial', 'Pakke Kessang',
       'Tiruvarur', 'East Midnapur', 'Bardez', 'Hooghiy', 'Pherzawl',
       'Jaintia Hills', 'West Medinipur', 'Lahaul And Spiti', 'Burdwan',
       'Bandipur', 'Mangan', 'Leh Ladakh', 'South 24 Pargana', 'Anugal',
       'Rajauri', 'Bijapurkar', 'Bagpat', 'Balotra', 'Ahilyanagar',
       'Didwana Kuchaman', 'Salumbar', 'Beawar'], dtype=object)

In [ ]:
STATE_MAPPING = {
    # (states)
    'Westbengal': 'West Bengal',
    'westbengal': 'West Bengal',
    'west bangal': 'West Bengal',
    'west bengli': 'West Bengal',
    'West Bangal': 'West Bengal',
    'WESTBENGAL' : 'West Bengal',
    'West Bengli': 'West Bengal',
    'Orissa': 'Odisha',
    'jammu kashmir': 'Jammu and Kashmir',
    'Uttaranchal': 'Uttarakhand',
    'Chhatisgarh': 'Chhattisgarh',
    'Pondicherry': 'Puducherry',
    'andaman nicobar islands': 'Andaman and Nicobar Islands',
    'daman diu': 'Daman and Diu',
    'dadra nagar haveli': 'Dadra and Nagar Haveli',
    'The Dadra And Nagar Haveli And Daman And Diu': 'Dadra And Nagar Haveli And Daman And Diu',
    'Tamilnadu': 'Tamil Nadu',

    #(localities)
    'Darbhanga': 'Bihar',
    'Puttenahalli': 'Karnataka',
    'Balanagar': 'Telangana',
    'Nagpur': 'Maharashtra',
    'Raja Annamalai Puram': 'Tamil Nadu',
    'Madanapalle': 'Andhra Pradesh',
    'Jaipur': 'Rajasthan'

}

In [ ]:
DISTRICT_MAP = {
    # Jammu & Kashmir
    "Punch": "Poonch",
    "Poonch": "Poonch",
    "Rajauri": "Rajouri",
    "Badgam": "Budgam",
    "Shupiyan": "Shopian",
    "Baramula": "Baramulla",

    # Telangana / Andhra Pradesh
    "Medchal Malkajgiri": "Medchal–Malkajgiri",
    "Medchalmalkajgiri": "Medchal–Malkajgiri",
    "Medchalâ\x88\x92Malkajgiri": "Medchal–Malkajgiri",
    "Rangareddi": "Ranga Reddy",
    "K V Rangareddy": "Ranga Reddy",
    "Y S R": "Ysr Kadapa",
    "Cuddapah": "Ysr Kadapa",

    # Karnataka
    "Tumkur": "Tumakuru",
    "Shimoga": "Shivamogga",
    "Bellary": "Ballari",
    "Belgaum": "Belagavi",
    "Gulbarga": "Kalaburagi",
    "Chickmagalur": "Chikkamagaluru",
    "Chikmagalur": "Chikkamagaluru",

    # West Bengal
    "Barddhaman": "Bardhaman",
    "Burdwan": "Bardhaman",
    "Haora": "Howrah",
    "Hawrah": "Howrah",
    "Hooghiy": "Hooghly",
    "Darjiling": "Darjeeling",
    "Medinipur": "Paschim Medinipur",

    # Odisha
    "Anugul": "Angul",
    "Khorda": "Khordha",
    "Baleshwar": "Balasore",
    "Sonapur": "Subarnapur",

    # Maharashtra
    "Ahmadnagar": "Ahmednagar",
    "Ahmed Nagar": "Ahmednagar",
    "Aurangabad": "Chhatrapati Sambhajinagar",
    "Osmanabad": "Dharashiv",
    "Bid": "Beed",
    "Gondia": "Gondiya",
    "Dist : Thane":"Thane",

    # Tamil Nadu
    "Tuticorin": "Thoothukkudi",
    "Tiruvarur": "Thiruvarur",
    "Viluppuram": "Villupuram",
    "Kanniyakumari": "Kanyakumari",

    # UP
    "Bara Banki": "Barabanki",
    "Raebareli": "Rae Bareli",
    "Sant Ravidas Nagar Bhadohi": "Bhadohi",
}

In [ ]:
for df in [df_bio, df_demo, df_enroll]:
    df['state'] = df['state'].apply(standardize_state)
    df['district'] = df['district'].apply(standardize_district)

In [ ]:
set(df_bio['state']) ^ set(df_demo['state']) ^ set(df_enroll['state'])

{'Andaman And Nicobar Islands',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Dadra And Nagar Haveli',
 'Dadra And Nagar Haveli And Daman And Diu',
 'Daman And Diu',
 'Delhi',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu And Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Ladakh',
 'Lakshadweep',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal'}

In [ ]:
bio_dates = set(df_bio['date']) #89
demo_dates = set(df_demo['date']) #95
enroll_dates = set(df_enroll['date']) #92

print("Bio only:", len(bio_dates - demo_dates - enroll_dates))
print("Demo only:", len(demo_dates - bio_dates - enroll_dates))
print("Enroll only:", len(enroll_dates - demo_dates - bio_dates))
print("Common to all:", len(bio_dates & demo_dates & enroll_dates))

Bio only: 0
Demo only: 4
Enroll only: 20
Common to all: 70

In [ ]:
common_dates = bio_dates & demo_dates & enroll_dates

df_bio = df_bio[df_bio['date'].isin(common_dates)]
df_demo = df_demo[df_demo['date'].isin(common_dates)]
df_enroll = df_enroll[df_enroll['date'].isin(common_dates)]

In [ ]:
for df in [df_bio, df_demo, df_enroll]:
    df['geo_key'] = (
        df['state'] + "_" +
        df['district'] + "_" +
        df['pincode'].astype(str)
    )

In [ ]:
df_bio

,date,state,district,pincode,bio_age_5_17,bio_age_17_,geo_key
21953,01-04-2025,Gujarat,Valsad,396051,331,407,Gujarat_Valsad_396051
21954,01-04-2025,Maharashtra,Palghar,401404,330,272,Maharashtra_Palghar_401404
21955,01-04-2025,Rajasthan,Jaipur,302019,220,463,Rajasthan_Jaipur_302019
21956,01-04-2025,Madhya Pradesh,Betul,460440,804,919,Madhya Pradesh_Betul_460440
21957,01-04-2025,Himachal Pradesh,Kangra,176021,51,75,Himachal Pradesh_Kangra_176021
...,...,...,...,...,...,...,...
1861103,29-12-2025,West Bengal,Uttar Dinajpur,733201,4,9,West Bengal_Uttar Dinajpur_733201
1861104,29-12-2025,West Bengal,Uttar Dinajpur,733213,0,1,West Bengal_Uttar Dinajpur_733213
1861105,29-12-2025,West Bengal,West Midnapore,721304,0,3,West Bengal_West Midnapore_721304
1861106,29-12-2025,West Bengal,West Midnapore,721451,2,0,West Bengal_West Midnapore_721451
1861107,29-12-2025,West Bengal,West Midnapore,721457,0,1,West Bengal_West Midnapore_721457

Raw pincode-level data is too granular.

For insights, we usually aggregate to:

District–Month

or State–Month

Example: District–Month aggregation

In [ ]:
bio_agg = df_bio.groupby(['date', 'state', 'district'])[
    ['bio_age_5_17', 'bio_age_17_']
].sum().reset_index()

demo_agg = df_demo.groupby(['date', 'state', 'district'])[
    ['demo_age_5_17', 'demo_age_17_']
].sum().reset_index()

enroll_agg = df_enroll.groupby(['date', 'state', 'district'])[
    ['age_0_5', 'age_5_17', 'age_18_greater']
].sum().reset_index()

In [ ]:
bio_agg

,date,state,district,bio_age_5_17,bio_age_17_
0,01-04-2025,Andaman And Nicobar Islands,Andamans,17,167
1,01-04-2025,Andaman And Nicobar Islands,Nicobar,151,117
2,01-04-2025,Andaman And Nicobar Islands,North And Middle Andaman,623,348
3,01-04-2025,Andaman And Nicobar Islands,South Andaman,839,482
4,01-04-2025,Andhra Pradesh,Adilabad,694,2822
...,...,...,...,...,...
57329,31-10-2025,West Bengal,South 24 Parganas,768,1479
57330,31-10-2025,West Bengal,South Dinajpur,4,16
57331,31-10-2025,West Bengal,South Twenty Four Parganas,43,330
57332,31-10-2025,West Bengal,Uttar Dinajpur,199,568
57333,31-10-2025,West Bengal,West Midnapore,26,162

For each (date, state, district):

Keep the row only if it exists in BOTH:

enrollment data

biometric data

❌ If a district has enrollment data but no biometric data that day, it is dropped.

In [ ]:
df_final = enroll_agg.merge(
    bio_agg,
    on=['date', 'state', 'district'],
    how='inner'
).merge(
    demo_agg,
    on=['date', 'state', 'district'],
    how='inner'
)

In [ ]:
df_final

,date,state,district,age_0_5,age_5_17,age_18_greater,bio_age_5_17,bio_age_17_,demo_age_5_17,demo_age_17_
0,01-04-2025,Assam,Bongaigaon,221,87,61,4512,1135,348,4007
1,01-04-2025,Bihar,Bhagalpur,678,534,26,14317,10270,930,4372
2,01-04-2025,Chandigarh,Chandigarh,86,21,10,4587,3334,3917,10968
3,01-04-2025,Chhattisgarh,Durg,336,38,10,3606,15585,1119,4996
4,01-04-2025,Chhattisgarh,Raipur,299,12,11,3770,15413,933,9415
...,...,...,...,...,...,...,...,...,...,...
50054,31-10-2025,West Bengal,South 24 Parganas,581,221,0,768,1479,525,9079
50055,31-10-2025,West Bengal,South Dinajpur,7,2,0,4,16,4,230
50056,31-10-2025,West Bengal,South Twenty Four Parganas,65,24,1,43,330,19,1432
50057,31-10-2025,West Bengal,Uttar Dinajpur,321,119,3,199,568,209,5799
50058,31-10-2025,West Bengal,West Midnapore,40,24,0,26,162,8,2040

from matplotlib import pyplot as plt
df_final['age_0_5'].plot(kind='hist', bins=20, title='age_0_5')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df_final['age_5_17'].plot(kind='hist', bins=20, title='age_5_17')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df_final['age_18_greater'].plot(kind='hist', bins=20, title='age_18_greater')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df_final['bio_age_5_17'].plot(kind='hist', bins=20, title='bio_age_5_17')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df_final.plot(kind='scatter', x='age_0_5', y='age_5_17', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df_final.plot(kind='scatter', x='age_5_17', y='age_18_greater', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df_final.plot(kind='scatter', x='age_18_greater', y='bio_age_5_17', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df_final.plot(kind='scatter', x='bio_age_5_17', y='bio_age_17_', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['date']
  ys = series['age_0_5']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df_final.sort_values('date', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('age_0_5')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['date']
  ys = series['age_5_17']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df_final.sort_values('date', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('age_5_17')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['date']
  ys = series['age_18_greater']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df_final.sort_values('date', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('age_18_greater')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['date']
  ys = series['bio_age_5_17']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df_final.sort_values('date', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('bio_age_5_17')

from matplotlib import pyplot as plt
df_final['age_0_5'].plot(kind='line', figsize=(8, 4), title='age_0_5')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df_final['age_5_17'].plot(kind='line', figsize=(8, 4), title='age_5_17')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df_final['age_18_greater'].plot(kind='line', figsize=(8, 4), title='age_18_greater')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df_final['bio_age_5_17'].plot(kind='line', figsize=(8, 4), title='bio_age_5_17')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
df_final.to_csv('/content/drive/MyDrive/UIDAI_DATA/UIDAI_DF.csv', index=False)